spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ZONAS_SEGURAS_DB;encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME:appuser25}
    password: ${DB_PASSWORD:App123Password!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

app:
  database:
    schema: PRUEBA00

server:
  port: 9091

logging:
  level:
    org.springframework.jdbc.core: DEBUG
